---
title: "20210227-phia_kmeans_jsg2145"
author: "Jared Garfinkel"
date: "2/27/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(psych)
library(corrplot)
library(factoextra)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	message = FALSE,
	# cache = TRUE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

# read in data

```{r}
bio <- read_csv(file = "./data/Shims22016adultbio.csv",
                      col_names = TRUE, 
                      col_types = NULL,
                      locale = default_locale(), 
                      na = c("", "NA"), 
                      quoted_na = TRUE,
                      quote = "\"", 
                      comment = "", 
                      trim_ws = TRUE, 
                      skip = 0,
                      n_max = Inf, 
                      progress = show_progress(), 
                      skip_empty_rows = TRUE) %>% 
  janitor::clean_names() %>% 
  mutate(across(.cols = c(-country, -householdid, -personid, -surveystdt, -resultvlc), ~as.numeric(.)))


ind <- read_csv(file = "./data/Shims22016adultind.csv") %>% 
  janitor::clean_names() %>% 
  mutate(across(.cols = c(-country, -householdid, -personid, -surveystdt), ~as.numeric(.x)))
```

# bt_status = 1, hivstatusfinal = 1

```{r}
bio_select <- bio %>%
    left_join(ind, by = c("personid", "country", "householdid", "bt_status", "gender", "age", "surveystdt", "hivstatusfinal", "varstrat", "varunit")) %>%
  # "avdprgmeth", "hivtstnors", "hivpostell", "sptgrgt", "stdl", "seekhelp", "unwantsxhelp")) %>%
    dplyr::select(-contains("vmpstw"), -contains("hivk"), -contains("casi"), -contains("intw")) %>%
    filter(bt_status == 1,
           hivstatusfinal == 1) %>%
           # arvstatus == 1) %>%
    dplyr::select(personid, age, gender, contains(c("status", "aware", "art", "vl", "tri90", "arv", "test", "hiv"))) %>%
    mutate( resultvlc = recode(resultvlc,
                    "< LLOD" = "1",
                    "< LLOQ: 20" = "20",
                    "< LLOQ: 40" = "40",
                    "< LLOQ: 400" = "400",
                    "< LLOQ: 839" = "839",
                    "> ULOQ 10000000" = "10000000"),
            resultvlc = as.numeric(resultvlc),
            vlunder200 = if_else(resultvlc < 200, 1, 2))

bio_select %>% 
  dplyr::select(vlunder200, everything()) %>% 
  group_by(vlunder200) %>%
  summarize(freq = n())
```

# clean the data

```{r}
recode_one_zero <- function(x) {
  if_else( is.na(x), 99,
  if_else( as.numeric(x) %in% c(0, 2), 0, # JSG
  if_else( as.numeric(x) == 1, 1, 99)
  ))
}

bio_select_mod <- bio_select %>%
    mutate( reported_positive = if_else( hivrslr == 1 | hivtstrslt == 1 | hivpsbp == 1 | hivrtpg == 1 | hivtfposy > 0, 1, 0, missing = 0),
            never_tested = if_else(hivtstever == 2, 1, 0, missing = 0),
            reported_negative = if_else(hivpsbp == 2 | (hivtsbp = 1 & hivrtpg == 2) | hivrslr == 2 | hivtstrslt == 2, 1, 0, missing = 0),
            pos_test_year = if_else(hivtfposy > 0, 1, 0),
            tested12mo = if_else(testedreceiveddetail %in% c(1,4), 1, 0),
            cd4testever = recode_one_zero(cd4testever),
            arvstakenev = if_else(arvstakenev == 1, 1, 0, missing = 0),
            arvscurrent = if_else(arvscurrent == 1, 1, 0, missing = 0),
            oth_art_care = if_else(arvtklb == 1 | arvcntn == 1 | hivcare == 1, 1, 0, missing = 0),
            across(-personid, recode_one_zero))

```

# Keep "arvstatus" in the model

```{r}
modelvars <- c("never_tested", "reported_negative", "reported_positive", "arvstakenev", "arvscurrent", "oth_art_care", "arvstatus")
# Remove all rows which have values other than 0 or 1
aware_patterns <- bio_select_mod %>% 
  dplyr::select( all_of(modelvars) ) %>%
  filter( across(everything(), ~ .x %in% c(0,1)))
  # mutate(across(.cols = c(reported_negative, never_tested), .fns = ~recode(., "0" = 1, "1" = 0)))
```

```{r}
set.seed(719)
kmfit = kmeans(aware_patterns, centers = 4)
# kmfit

output2 = NULL
for(i in 1:length(kmfit$cluster)) {
  output2[[i]] = tibble(kmfit$cluster[[i]])
}

output2_df = bind_rows(output2) %>% 
  rename("cluster" = "kmfit$cluster[[i]]")

aware_patterns %>% 
  add_column(cluster = pull(output2_df, cluster)) %>% 
  dplyr::select(cluster, everything()) %>% 
  arrange(cluster) %>% 
  filter(cluster==4)

set.seed(719)
km_vis <- fviz_cluster(list(data = aware_patterns, cluster = kmfit$cluster),
                       ellipse.type = "convex", 
                       geom = c("point","text"),
                       labelsize = 10) + 
  labs(title = "K-means") 

km_vis
```

