---
title: "phia_lcaResults_jsg2145"
author: "Jared Garfinkel"
date: "1/11/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(randomLCA)
library(gt)
library(caret)
knitr::opts_chunk$set(
	echo = FALSE,
	warning = FALSE,
	message = FALSE,
	# cache = TRUE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

# read in data

```{r}
bio <- read_csv(file = "./data/Shims22016adultbio.csv",
                      col_names = TRUE, 
                      col_types = NULL,
                      locale = default_locale(), 
                      na = c("", "NA"), 
                      quoted_na = TRUE,
                      quote = "\"", 
                      comment = "", 
                      trim_ws = TRUE, 
                      skip = 0,
                      n_max = Inf, 
                      progress = show_progress(), 
                      skip_empty_rows = TRUE) %>% 
  janitor::clean_names() %>% 
  mutate(across(.cols = c(-country, -householdid, -personid, -surveystdt, -resultvlc), ~as.numeric(.x)))


ind <- read_csv(file = "./data/Shims22016adultind.csv") %>% 
  janitor::clean_names() %>% 
  mutate(across(.cols = c(-country, -householdid, -personid, -surveystdt), ~as.numeric(.x)))
```

# bt_status = 1, hivstatusfinal = 1, arvstatus = 1

## This is the primary difference between this data set and others

```{r}
bio_select <- bio %>% 
    left_join(ind, by = c("personid", "country", "householdid", "bt_status", "gender", "age", "surveystdt", "hivstatusfinal", "varstrat", "varunit")) %>% 
  # "avdprgmeth", "hivtstnors", "hivpostell", "sptgrgt", "stdl", "seekhelp", "unwantsxhelp")) %>%
    select(-contains("vmpstw"), -contains("hivk"), -contains("casi"), -contains("intw")) %>%
    filter(bt_status == 1,
           hivstatusfinal == 1,
           arvstatus == 1) %>% 
    select(personid, age, gender, contains(c("status", "aware", "art", "vl", "tri90", "arv", "test", "hiv"))) %>% 
    mutate( resultvlc = recode(resultvlc, 
                    "< LLOD" = "1",
                    "< LLOQ: 20" = "20",
                    "< LLOQ: 40" = "40",
                    "< LLOQ: 400" = "400",
                    "< LLOQ: 839" = "839",
                    "> ULOQ 10000000" = "10000000"),
            resultvlc = as.numeric(resultvlc),
            vlunder200 = if_else(resultvlc < 200, 1, 2)) 

bio_select %>% 
  select(vlunder200, everything()) %>% 
  group_by(vlunder200) %>%
  summarize(freq = n())
```

# clean the data

```{r}
recode_one_zero <- function(x) {
  if_else( is.na(x), 99,
  if_else( as.numeric(x) %in% c(0, 2), 0, # JSG
  if_else( as.numeric(x) == 1, 1, 99)
  ))
}

bio_select_mod <- bio_select %>%
    mutate( reported_positive = if_else( hivrslr == 1 | hivtstrslt == 1 | hivpsbp == 1 | hivrtpg == 1 | hivtfposy > 0, 1, 0, missing = 0),
            never_tested = if_else(hivtstever == 2, 1, 0, missing = 0),
            reported_negative = if_else(hivpsbp == 2 | (hivtsbp = 1 & hivrtpg == 2) | hivrslr == 2 | hivtstrslt == 2, 1, 0, missing = 0),
            pos_test_year = if_else(hivtfposy > 0, 1, 0),
            tested12mo = if_else(testedreceiveddetail %in% c(1,4), 1, 0),
            cd4testever = recode_one_zero(cd4testever),
            arvstakenev = if_else(arvstakenev == 1, 1, 0, missing = 0),
            arvscurrent = if_else(arvscurrent == 1, 1, 0, missing = 0),
            oth_art_care = if_else(arvtklb == 1 | arvcntn == 1 | hivcare == 1, 1, 0, missing = 0),
            across(-personid, recode_one_zero))

bio_select_var = bio %>% 
  filter(bt_status == 1,
         hivstatusfinal == 1) %>% 
  select(personid, awareartselfreported)
```

# make the LCA model, 4 classes

```{r}
modelvars <- c("never_tested", "reported_negative", "reported_positive", "arvstakenev", "arvscurrent", "oth_art_care", "vlunder200")
# Remove all rows which have values other than 0 or 1
aware_patterns <- bio_select_mod %>% 
  select( all_of(modelvars) ) %>%
  filter( across(everything(), ~ .x %in% c(0,1)))
# aware_patterns$vlunder200
set.seed(719)
awareARTVL.lca4 <- randomLCA(aware_patterns, nclass = 4, quadpoints = 30)

outcomep <- round(awareARTVL.lca4$outcomep, 4)
colnames(outcomep) <- names(aware_patterns)

# OutcomeProbs.Table.AwareARTVL <- as.data.frame( cbind( Class = c(1, 2, 3), outcomep)) %>%
#   mutate(across(-Class, as.numeric))
```



```{r}
set.seed(719)
lca_out_vls4 = postClassProbs(awareARTVL.lca4) %>% 
  janitor::clean_names() %>% 
  mutate(class = if_else(class_1 > class_2, 
                         if_else(class_2 > class_3,
                                 if_else(class_3 > class_4, 1,
                                         if_else(class_4 > class_1, 4, 1)),
                                 if_else(class_3 > class_1,
                                         if_else(class_1 > class_4, 3,
                                                 if_else(class_4 > class_3, 4, 3)),
                                         if_else(class_1 > class_4, 1, 4))),
                         if_else(class_2 > class_3, 
                                 if_else(class_3 > class_4, 2,
                                         if_else(class_4 > class_2, 4, 2)),
                                 if_else(class_4 > class_3, 4, 3))))
```


```{r, fig.height = 10, fig.width = 14}
postClassProbs(awareARTVL.lca4) %>% 
  janitor::clean_names() %>% 
  mutate(class = if_else(class_1 > class_2, 
                         if_else(class_2 > class_3,
                                 if_else(class_3 > class_4, 1,
                                         if_else(class_4 > class_1, 4, 1)),
                                 if_else(class_3 > class_1,
                                         if_else(class_1 > class_4, 3,
                                                 if_else(class_4 > class_3, 4, 3)),
                                         if_else(class_1 > class_4, 1, 4))),
                         if_else(class_2 > class_3, 
                                 if_else(class_3 > class_4, 2,
                                         if_else(class_4 > class_2, 4, 2)),
                                 if_else(class_4 > class_3, 4, 3)))) %>% 
  select(never_tested:freq, class) %>% 
  arrange(class, vlunder200) %>% 
  gt() %>% 
  tab_row_group(group = "class_1",
                rows = c(1:3)) %>% 
  tab_row_group(group = "class_2",
                rows = c(4:12)) %>% 
  tab_row_group(group = "class_3",
                rows = c(13:16)) %>% 
  tab_row_group(group = "class_4",
                rows = c(17:20)) %>% 
  tab_spanner(label = "profile",
              columns = vars(never_tested, reported_negative, reported_positive, arvstakenev, arvscurrent, oth_art_care, vlunder200)) %>% 
  tab_spanner(label = "cases",
              columns = vars(freq)) %>% 
  tab_spanner(label = "LCA Class",
              columns = vars(class)) %>% 
  gtsave("20210111-4_class_profiles_lesotho.html")

postClassProbs(awareARTVL.lca4) %>%
  janitor::clean_names() %>%
  mutate(class = if_else(class_1 > class_2,
                         if_else(class_2 > class_3,
                                 if_else(class_3 > class_4, 1,
                                         if_else(class_4 > class_1, 4, 1)),
                                 if_else(class_3 > class_1,
                                         if_else(class_1 > class_4, 3,
                                                 if_else(class_4 > class_3, 4, 3)),
                                         if_else(class_1 > class_4, 1, 4))),
                         if_else(class_2 > class_3,
                                 if_else(class_3 > class_4, 2,
                                         if_else(class_4 > class_2, 4, 2)),
                                 if_else(class_4 > class_3, 4, 3)))) %>%
  select(never_tested:freq, class) %>%
  mutate(class = if_else(class %in% c(2, 4), "aware", "unaware")) %>%
  group_by(class, vlunder200) %>%
  summarize(freq = sum(freq)) %>%
  group_by(class) %>%
  mutate(p_vls = freq/sum(freq))
```

# LCA model, 3 classes

```{r}
modelvars <- c("never_tested", "reported_negative", "reported_positive", "arvstakenev", "arvscurrent", "oth_art_care", "vlunder200")
# Remove all rows which have values other than 0 or 1
aware_patterns <- bio_select_mod %>% 
  select( all_of(modelvars) ) %>%
  filter( across(everything(), ~ .x %in% c(0,1)))
# aware_patterns$vlunder200
set.seed(719)
awareARTVL.lca3 <- randomLCA(aware_patterns, nclass = 3, quadpoints = 30)

outcomep <- round(awareARTVL.lca3$outcomep, 4)
colnames(outcomep) <- names(aware_patterns)

# OutcomeProbs.Table.AwareARTVL <- as.data.frame( cbind( Class = c(1, 2, 3), outcomep)) %>%
#   mutate(across(-Class, as.numeric))
```



```{r}
set.seed(719)
lca_out_vls3 = postClassProbs(awareARTVL.lca3) %>% 
  janitor::clean_names() %>% 
  mutate(class = if_else(class_1 > class_2, 
                         if_else(class_2 > class_3, 1,
                                 if_else(class_3 > class_1, 3, 1)), 
                         if_else(class_2 > class_3, 2, 3)))
```


```{r, fig.height = 10, fig.width = 14}
postClassProbs(awareARTVL.lca3) %>% 
  janitor::clean_names() %>% 
  mutate(class = if_else(class_1 > class_2, 
                         if_else(class_2 > class_3, 1,
                                 if_else(class_3 > class_1, 3, 1)), 
                         if_else(class_2 > class_3, 2, 3))) %>% 
  select(never_tested:freq, class) %>% 
  arrange(class, vlunder200) %>% 
  gt() %>% 
  tab_row_group(group = "class_1",
                rows = c(1:9)) %>% 
  tab_row_group(group = "class_2",
                rows = c(10:12)) %>% 
  tab_row_group(group = "class_3",
                rows = c(13:20)) %>% 
  # tab_row_group(group = "class_4",
  #               rows = c(17:20)) %>% 
  tab_spanner(label = "profile",
              columns = vars(never_tested, reported_negative, reported_positive, arvstakenev, arvscurrent, oth_art_care, vlunder200)) %>% 
  tab_spanner(label = "cases",
              columns = vars(freq)) %>% 
  tab_spanner(label = "LCA Class",
              columns = vars(class)) %>% 
  gtsave("20210111-3_class_profiles_lesotho.html")
```

The model above is difficult to interpret, because the 2nd class includes those who were never tested and those who reported a positive result.

```{r, include = FALSE, eval = FALSE, fig.height = 10, fig.width = 14}
postClassProbs(awareARTVL.lca4) %>%
  janitor::clean_names() %>%
  mutate(class = if_else(class_1 > class_2,
                         if_else(class_2 > class_3,
                                 if_else(class_3 > class_4, 1,
                                         if_else(class_4 > class_1, 4, 1)),
                                 if_else(class_3 > class_1,
                                         if_else(class_1 > class_4, 3,
                                                 if_else(class_4 > class_3, 4, 3)),
                                         if_else(class_1 > class_4, 1, 4))),
                         if_else(class_2 > class_3,
                                 if_else(class_3 > class_4, 2,
                                         if_else(class_4 > class_2, 4, 2)),
                                 if_else(class_4 > class_3, 4, 3)))) %>%
  select(never_tested:freq, class) %>%
  mutate(class = if_else(class %in% c(2, 4), "aware", "unaware")) %>%
  group_by(class, vlunder200) %>%
  summarize(freq = sum(freq)) %>%
  group_by(class) %>%
  mutate(p_vls = freq/sum(freq))
```

